package jp.go.meti.drone.api.auth.repository;

import java.util.List;
import jp.go.meti.drone.api.auth.repository.entity.DipsAccessEntity;
import jp.go.meti.drone.api.auth.repository.entity.DipsAccessEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface DipsAccessRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    long countByExample(DipsAccessEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int deleteByExample(DipsAccessEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int deleteByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int insert(DipsAccessEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int insertSelective(DipsAccessEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    List<DipsAccessEntity> selectByExampleWithRowbounds(DipsAccessEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    List<DipsAccessEntity> selectByExample(DipsAccessEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    DipsAccessEntity selectByPrimaryKey(String clientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int updateByExampleSelective(@Param("row") DipsAccessEntity row, @Param("example") DipsAccessEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int updateByExample(@Param("row") DipsAccessEntity row, @Param("example") DipsAccessEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int updateByPrimaryKeySelective(DipsAccessEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    int updateByPrimaryKey(DipsAccessEntity row);
}