package jp.go.meti.drone.relatedpartiesnotice.tenant.repository.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import jp.go.meti.drone.relatedpartiesnotice.tenant.repository.entity.AirwayTenantAssociationEntity;

/**
 * 航路事業者関連情報取得 リポジトリ
 *
 * @version 1.0 2024/11/08
 */
@Mapper
public interface AirwayTenantAssociationRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table droneairway.airway_ｔenant_association
	 * 
	 * @param operatorId 事業者ID
	 * @return 返答
	 * @mbg.generated Tue Nov 05 18:08:00 JST 2024
	 */
	List<AirwayTenantAssociationEntity> selectByPrimaryKey(@Param("operatorId") String operatorId);
	
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table droneairway.airway_ｔenant_association
	 * 
	 * @param operatorId 航路ID
	 * @return 返答
	 * @mbg.generated Tue Nov 05 18:08:00 JST 2024
	 */
	List<AirwayTenantAssociationEntity> selectByAirwayId(@Param("airwayId") String airwayId);

}
