package jp.go.meti.drone.relatedpartiesnotice.tenant.repository.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import jp.go.meti.drone.relatedpartiesnotice.tenant.repository.entity.TenantRoleEntity;

/**
 * 事業者権限リポジトリ
 */
@Mapper
public interface TenantRoleRepository {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table droneairway2.tenant_role
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	List<TenantRoleEntity> selectByPrimaryKey(String operatorId);

}