package jp.go.meti.drone.swim.repository.mapper;

import java.util.List;
import jp.go.meti.drone.swim.repository.entity.SwimMaxFallRangeEntity;
import jp.go.meti.drone.swim.repository.entity.SwimMaxFallRangeEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SwimMaxFallRangeRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    long countByExample(SwimMaxFallRangeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByExample(SwimMaxFallRangeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insert(SwimMaxFallRangeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insertSelective(SwimMaxFallRangeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimMaxFallRangeEntity> selectByExampleWithRowbounds(SwimMaxFallRangeEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimMaxFallRangeEntity> selectByExample(SwimMaxFallRangeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    SwimMaxFallRangeEntity selectByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExampleSelective(@Param("row") SwimMaxFallRangeEntity row, @Param("example") SwimMaxFallRangeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExample(@Param("row") SwimMaxFallRangeEntity row, @Param("example") SwimMaxFallRangeEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKeySelective(SwimMaxFallRangeEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKey(SwimMaxFallRangeEntity row);
}