package jp.go.meti.drone.swim.repository.mapper;

import java.util.List;
import jp.go.meti.drone.swim.repository.entity.SwimFeedbackEntity;
import jp.go.meti.drone.swim.repository.entity.SwimFeedbackEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SwimFeedbackRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    long countByExample(SwimFeedbackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByExample(SwimFeedbackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId, @Param("historyIndex") Integer historyIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insert(SwimFeedbackEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insertSelective(SwimFeedbackEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimFeedbackEntity> selectByExampleWithRowbounds(SwimFeedbackEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimFeedbackEntity> selectByExample(SwimFeedbackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    SwimFeedbackEntity selectByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId, @Param("historyIndex") Integer historyIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExampleSelective(@Param("row") SwimFeedbackEntity row, @Param("example") SwimFeedbackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExample(@Param("row") SwimFeedbackEntity row, @Param("example") SwimFeedbackEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKeySelective(SwimFeedbackEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_feedback
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKey(SwimFeedbackEntity row);
}