package jp.go.meti.drone.swim.repository.mapper;

import java.util.List;
import jp.go.meti.drone.swim.repository.entity.SwimMaxFallRangeHistoryEntity;
import jp.go.meti.drone.swim.repository.entity.SwimMaxFallRangeHistoryEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SwimMaxFallRangeHistoryRepository {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    long countByExample(SwimMaxFallRangeHistoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByExample(SwimMaxFallRangeHistoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int deleteByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId, @Param("historyIndex") Integer historyIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insert(SwimMaxFallRangeHistoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int insertSelective(SwimMaxFallRangeHistoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimMaxFallRangeHistoryEntity> selectByExampleWithRowbounds(SwimMaxFallRangeHistoryEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    List<SwimMaxFallRangeHistoryEntity> selectByExample(SwimMaxFallRangeHistoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    SwimMaxFallRangeHistoryEntity selectByPrimaryKey(@Param("businessNumber") String businessNumber, @Param("maxFallRangeId") String maxFallRangeId, @Param("historyIndex") Integer historyIndex);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExampleSelective(@Param("row") SwimMaxFallRangeHistoryEntity row, @Param("example") SwimMaxFallRangeHistoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByExample(@Param("row") SwimMaxFallRangeHistoryEntity row, @Param("example") SwimMaxFallRangeHistoryEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKeySelective(SwimMaxFallRangeHistoryEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    int updateByPrimaryKey(SwimMaxFallRangeHistoryEntity row);
}