server:
  port: 8283
logging.level:
  '[com.zaxxer.hikari]': DEBUG
  '[jp.go.meti.drone]': DEBUG
  '[jp.go.meti.drone.com.common.logging.aspect.LoggingAspect]' : DEBUG

drone:
  commom:
    logging:
      aspect:
        resultByteLoggingLimitSize: 1999
        resultStringLoggingLimitSize: 999
drone.common.auth:
  enabled: false
  http-basic:
    enabled: true

spring.transaction:
  rollback-on-commit-failure: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true

spring.messages.basename: messages/messages

# MQTT
mqtt:
  send-client-id: ${MQTT_CLIENT:mqttSampleClient}
  qos: 2
  retry-cnt-max: 2
  ssl: false
  clean-session: true
  time-to-wait: 0
  reconnect: true
  connect-timeout: 10
  client:
    mqttsDockerClient:
      base-url: tcp://${MQTT_HOSTNAME:localhost}:${MQTT_PORT:1883}
      username: ${MQTT_USERNAME:admin}
      password: ${MQTT_PASSWORD:admin}
    noticeMqttClient:
      base-url: tcp://${MQTT_HOSTNAME:localhost}:${MQTT_PORT:1883}
      username: ${MQTT_USERNAME:admin}
      password: ${MQTT_PASSWORD:admin}