package jp.go.meti.drone.swim.repository.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class SwimMaxFallRangeHistoryEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected boolean forUpdate;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public SwimMaxFallRangeHistoryEntityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public boolean isForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return forUpdate;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusinessNumberIsNull() {
            addCriterion("business_number is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIsNotNull() {
            addCriterion("business_number is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberEqualTo(String value) {
            addCriterion("business_number =", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotEqualTo(String value) {
            addCriterion("business_number <>", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThan(String value) {
            addCriterion("business_number >", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThanOrEqualTo(String value) {
            addCriterion("business_number >=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThan(String value) {
            addCriterion("business_number <", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThanOrEqualTo(String value) {
            addCriterion("business_number <=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLike(String value) {
            addCriterion("business_number like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotLike(String value) {
            addCriterion("business_number not like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIn(List<String> values) {
            addCriterion("business_number in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotIn(List<String> values) {
            addCriterion("business_number not in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberBetween(String value1, String value2) {
            addCriterion("business_number between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotBetween(String value1, String value2) {
            addCriterion("business_number not between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIsNull() {
            addCriterion("max_fall_range_id is null");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIsNotNull() {
            addCriterion("max_fall_range_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdEqualTo(String value) {
            addCriterion("max_fall_range_id =", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotEqualTo(String value) {
            addCriterion("max_fall_range_id <>", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdGreaterThan(String value) {
            addCriterion("max_fall_range_id >", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdGreaterThanOrEqualTo(String value) {
            addCriterion("max_fall_range_id >=", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLessThan(String value) {
            addCriterion("max_fall_range_id <", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLessThanOrEqualTo(String value) {
            addCriterion("max_fall_range_id <=", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLike(String value) {
            addCriterion("max_fall_range_id like", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotLike(String value) {
            addCriterion("max_fall_range_id not like", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIn(List<String> values) {
            addCriterion("max_fall_range_id in", values, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotIn(List<String> values) {
            addCriterion("max_fall_range_id not in", values, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdBetween(String value1, String value2) {
            addCriterion("max_fall_range_id between", value1, value2, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotBetween(String value1, String value2) {
            addCriterion("max_fall_range_id not between", value1, value2, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexIsNull() {
            addCriterion("history_index is null");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexIsNotNull() {
            addCriterion("history_index is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexEqualTo(Integer value) {
            addCriterion("history_index =", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexNotEqualTo(Integer value) {
            addCriterion("history_index <>", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexGreaterThan(Integer value) {
            addCriterion("history_index >", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("history_index >=", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexLessThan(Integer value) {
            addCriterion("history_index <", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexLessThanOrEqualTo(Integer value) {
            addCriterion("history_index <=", value, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexIn(List<Integer> values) {
            addCriterion("history_index in", values, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexNotIn(List<Integer> values) {
            addCriterion("history_index not in", values, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexBetween(Integer value1, Integer value2) {
            addCriterion("history_index between", value1, value2, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andHistoryIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("history_index not between", value1, value2, "historyIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureIdIsNull() {
            addCriterion("feature_id is null");
            return (Criteria) this;
        }

        public Criteria andFeatureIdIsNotNull() {
            addCriterion("feature_id is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureIdEqualTo(String value) {
            addCriterion("feature_id =", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdNotEqualTo(String value) {
            addCriterion("feature_id <>", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdGreaterThan(String value) {
            addCriterion("feature_id >", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdGreaterThanOrEqualTo(String value) {
            addCriterion("feature_id >=", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdLessThan(String value) {
            addCriterion("feature_id <", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdLessThanOrEqualTo(String value) {
            addCriterion("feature_id <=", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdLike(String value) {
            addCriterion("feature_id like", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdNotLike(String value) {
            addCriterion("feature_id not like", value, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdIn(List<String> values) {
            addCriterion("feature_id in", values, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdNotIn(List<String> values) {
            addCriterion("feature_id not in", values, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdBetween(String value1, String value2) {
            addCriterion("feature_id between", value1, value2, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureIdNotBetween(String value1, String value2) {
            addCriterion("feature_id not between", value1, value2, "featureId");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidIsNull() {
            addCriterion("feature_timesliceid is null");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidIsNotNull() {
            addCriterion("feature_timesliceid is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidEqualTo(String value) {
            addCriterion("feature_timesliceid =", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidNotEqualTo(String value) {
            addCriterion("feature_timesliceid <>", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidGreaterThan(String value) {
            addCriterion("feature_timesliceid >", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidGreaterThanOrEqualTo(String value) {
            addCriterion("feature_timesliceid >=", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidLessThan(String value) {
            addCriterion("feature_timesliceid <", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidLessThanOrEqualTo(String value) {
            addCriterion("feature_timesliceid <=", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidLike(String value) {
            addCriterion("feature_timesliceid like", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidNotLike(String value) {
            addCriterion("feature_timesliceid not like", value, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidIn(List<String> values) {
            addCriterion("feature_timesliceid in", values, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidNotIn(List<String> values) {
            addCriterion("feature_timesliceid not in", values, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidBetween(String value1, String value2) {
            addCriterion("feature_timesliceid between", value1, value2, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureTimesliceidNotBetween(String value1, String value2) {
            addCriterion("feature_timesliceid not between", value1, value2, "featureTimesliceid");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionIsNull() {
            addCriterion("feature_begin_position is null");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionIsNotNull() {
            addCriterion("feature_begin_position is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionEqualTo(String value) {
            addCriterion("feature_begin_position =", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionNotEqualTo(String value) {
            addCriterion("feature_begin_position <>", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionGreaterThan(String value) {
            addCriterion("feature_begin_position >", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionGreaterThanOrEqualTo(String value) {
            addCriterion("feature_begin_position >=", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionLessThan(String value) {
            addCriterion("feature_begin_position <", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionLessThanOrEqualTo(String value) {
            addCriterion("feature_begin_position <=", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionLike(String value) {
            addCriterion("feature_begin_position like", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionNotLike(String value) {
            addCriterion("feature_begin_position not like", value, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionIn(List<String> values) {
            addCriterion("feature_begin_position in", values, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionNotIn(List<String> values) {
            addCriterion("feature_begin_position not in", values, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionBetween(String value1, String value2) {
            addCriterion("feature_begin_position between", value1, value2, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureBeginPositionNotBetween(String value1, String value2) {
            addCriterion("feature_begin_position not between", value1, value2, "featureBeginPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionIsNull() {
            addCriterion("feature_end_position is null");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionIsNotNull() {
            addCriterion("feature_end_position is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionEqualTo(String value) {
            addCriterion("feature_end_position =", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionNotEqualTo(String value) {
            addCriterion("feature_end_position <>", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionGreaterThan(String value) {
            addCriterion("feature_end_position >", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionGreaterThanOrEqualTo(String value) {
            addCriterion("feature_end_position >=", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionLessThan(String value) {
            addCriterion("feature_end_position <", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionLessThanOrEqualTo(String value) {
            addCriterion("feature_end_position <=", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionLike(String value) {
            addCriterion("feature_end_position like", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionNotLike(String value) {
            addCriterion("feature_end_position not like", value, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionIn(List<String> values) {
            addCriterion("feature_end_position in", values, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionNotIn(List<String> values) {
            addCriterion("feature_end_position not in", values, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionBetween(String value1, String value2) {
            addCriterion("feature_end_position between", value1, value2, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureEndPositionNotBetween(String value1, String value2) {
            addCriterion("feature_end_position not between", value1, value2, "featureEndPosition");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorIsNull() {
            addCriterion("feature_designator is null");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorIsNotNull() {
            addCriterion("feature_designator is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorEqualTo(String value) {
            addCriterion("feature_designator =", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorNotEqualTo(String value) {
            addCriterion("feature_designator <>", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorGreaterThan(String value) {
            addCriterion("feature_designator >", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorGreaterThanOrEqualTo(String value) {
            addCriterion("feature_designator >=", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorLessThan(String value) {
            addCriterion("feature_designator <", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorLessThanOrEqualTo(String value) {
            addCriterion("feature_designator <=", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorLike(String value) {
            addCriterion("feature_designator like", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorNotLike(String value) {
            addCriterion("feature_designator not like", value, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorIn(List<String> values) {
            addCriterion("feature_designator in", values, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorNotIn(List<String> values) {
            addCriterion("feature_designator not in", values, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorBetween(String value1, String value2) {
            addCriterion("feature_designator between", value1, value2, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureDesignatorNotBetween(String value1, String value2) {
            addCriterion("feature_designator not between", value1, value2, "featureDesignator");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexIsNull() {
            addCriterion("feature_activation_index is null");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexIsNotNull() {
            addCriterion("feature_activation_index is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexEqualTo(Integer value) {
            addCriterion("feature_activation_index =", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexNotEqualTo(Integer value) {
            addCriterion("feature_activation_index <>", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexGreaterThan(Integer value) {
            addCriterion("feature_activation_index >", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("feature_activation_index >=", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexLessThan(Integer value) {
            addCriterion("feature_activation_index <", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexLessThanOrEqualTo(Integer value) {
            addCriterion("feature_activation_index <=", value, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexIn(List<Integer> values) {
            addCriterion("feature_activation_index in", values, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexNotIn(List<Integer> values) {
            addCriterion("feature_activation_index not in", values, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexBetween(Integer value1, Integer value2) {
            addCriterion("feature_activation_index between", value1, value2, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureActivationIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("feature_activation_index not between", value1, value2, "featureActivationIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexIsNull() {
            addCriterion("feature_geometry_component_index is null");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexIsNotNull() {
            addCriterion("feature_geometry_component_index is not null");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexEqualTo(Integer value) {
            addCriterion("feature_geometry_component_index =", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexNotEqualTo(Integer value) {
            addCriterion("feature_geometry_component_index <>", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexGreaterThan(Integer value) {
            addCriterion("feature_geometry_component_index >", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("feature_geometry_component_index >=", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexLessThan(Integer value) {
            addCriterion("feature_geometry_component_index <", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexLessThanOrEqualTo(Integer value) {
            addCriterion("feature_geometry_component_index <=", value, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexIn(List<Integer> values) {
            addCriterion("feature_geometry_component_index in", values, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexNotIn(List<Integer> values) {
            addCriterion("feature_geometry_component_index not in", values, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexBetween(Integer value1, Integer value2) {
            addCriterion("feature_geometry_component_index between", value1, value2, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andFeatureGeometryComponentIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("feature_geometry_component_index not between", value1, value2, "featureGeometryComponentIndex");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidIsNull() {
            addCriterion("object10_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidIsNotNull() {
            addCriterion("object10_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidEqualTo(String value) {
            addCriterion("object10_objid =", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidNotEqualTo(String value) {
            addCriterion("object10_objid <>", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidGreaterThan(String value) {
            addCriterion("object10_objid >", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object10_objid >=", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidLessThan(String value) {
            addCriterion("object10_objid <", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidLessThanOrEqualTo(String value) {
            addCriterion("object10_objid <=", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidLike(String value) {
            addCriterion("object10_objid like", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidNotLike(String value) {
            addCriterion("object10_objid not like", value, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidIn(List<String> values) {
            addCriterion("object10_objid in", values, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidNotIn(List<String> values) {
            addCriterion("object10_objid not in", values, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidBetween(String value1, String value2) {
            addCriterion("object10_objid between", value1, value2, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10ObjidNotBetween(String value1, String value2) {
            addCriterion("object10_objid not between", value1, value2, "object10Objid");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexIsNull() {
            addCriterion("object10_timeinterval_index is null");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexIsNotNull() {
            addCriterion("object10_timeinterval_index is not null");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexEqualTo(Integer value) {
            addCriterion("object10_timeinterval_index =", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexNotEqualTo(Integer value) {
            addCriterion("object10_timeinterval_index <>", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexGreaterThan(Integer value) {
            addCriterion("object10_timeinterval_index >", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("object10_timeinterval_index >=", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexLessThan(Integer value) {
            addCriterion("object10_timeinterval_index <", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexLessThanOrEqualTo(Integer value) {
            addCriterion("object10_timeinterval_index <=", value, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexIn(List<Integer> values) {
            addCriterion("object10_timeinterval_index in", values, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexNotIn(List<Integer> values) {
            addCriterion("object10_timeinterval_index not in", values, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexBetween(Integer value1, Integer value2) {
            addCriterion("object10_timeinterval_index between", value1, value2, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject10TimeintervalIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("object10_timeinterval_index not between", value1, value2, "object10TimeintervalIndex");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidIsNull() {
            addCriterion("object13_par_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidIsNotNull() {
            addCriterion("object13_par_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidEqualTo(String value) {
            addCriterion("object13_par_objid =", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidNotEqualTo(String value) {
            addCriterion("object13_par_objid <>", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidGreaterThan(String value) {
            addCriterion("object13_par_objid >", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object13_par_objid >=", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidLessThan(String value) {
            addCriterion("object13_par_objid <", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidLessThanOrEqualTo(String value) {
            addCriterion("object13_par_objid <=", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidLike(String value) {
            addCriterion("object13_par_objid like", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidNotLike(String value) {
            addCriterion("object13_par_objid not like", value, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidIn(List<String> values) {
            addCriterion("object13_par_objid in", values, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidNotIn(List<String> values) {
            addCriterion("object13_par_objid not in", values, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidBetween(String value1, String value2) {
            addCriterion("object13_par_objid between", value1, value2, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ParObjidNotBetween(String value1, String value2) {
            addCriterion("object13_par_objid not between", value1, value2, "object13ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidIsNull() {
            addCriterion("object13_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidIsNotNull() {
            addCriterion("object13_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidEqualTo(String value) {
            addCriterion("object13_objid =", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidNotEqualTo(String value) {
            addCriterion("object13_objid <>", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidGreaterThan(String value) {
            addCriterion("object13_objid >", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object13_objid >=", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidLessThan(String value) {
            addCriterion("object13_objid <", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidLessThanOrEqualTo(String value) {
            addCriterion("object13_objid <=", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidLike(String value) {
            addCriterion("object13_objid like", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidNotLike(String value) {
            addCriterion("object13_objid not like", value, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidIn(List<String> values) {
            addCriterion("object13_objid in", values, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidNotIn(List<String> values) {
            addCriterion("object13_objid not in", values, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidBetween(String value1, String value2) {
            addCriterion("object13_objid between", value1, value2, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject13ObjidNotBetween(String value1, String value2) {
            addCriterion("object13_objid not between", value1, value2, "object13Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidIsNull() {
            addCriterion("object24_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidIsNotNull() {
            addCriterion("object24_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidEqualTo(String value) {
            addCriterion("object24_objid =", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidNotEqualTo(String value) {
            addCriterion("object24_objid <>", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidGreaterThan(String value) {
            addCriterion("object24_objid >", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object24_objid >=", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidLessThan(String value) {
            addCriterion("object24_objid <", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidLessThanOrEqualTo(String value) {
            addCriterion("object24_objid <=", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidLike(String value) {
            addCriterion("object24_objid like", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidNotLike(String value) {
            addCriterion("object24_objid not like", value, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidIn(List<String> values) {
            addCriterion("object24_objid in", values, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidNotIn(List<String> values) {
            addCriterion("object24_objid not in", values, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidBetween(String value1, String value2) {
            addCriterion("object24_objid between", value1, value2, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24ObjidNotBetween(String value1, String value2) {
            addCriterion("object24_objid not between", value1, value2, "object24Objid");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexIsNull() {
            addCriterion("object24_air_space_volume_index is null");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexIsNotNull() {
            addCriterion("object24_air_space_volume_index is not null");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexEqualTo(Integer value) {
            addCriterion("object24_air_space_volume_index =", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexNotEqualTo(Integer value) {
            addCriterion("object24_air_space_volume_index <>", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexGreaterThan(Integer value) {
            addCriterion("object24_air_space_volume_index >", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("object24_air_space_volume_index >=", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexLessThan(Integer value) {
            addCriterion("object24_air_space_volume_index <", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexLessThanOrEqualTo(Integer value) {
            addCriterion("object24_air_space_volume_index <=", value, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexIn(List<Integer> values) {
            addCriterion("object24_air_space_volume_index in", values, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexNotIn(List<Integer> values) {
            addCriterion("object24_air_space_volume_index not in", values, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexBetween(Integer value1, Integer value2) {
            addCriterion("object24_air_space_volume_index between", value1, value2, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject24AirSpaceVolumeIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("object24_air_space_volume_index not between", value1, value2, "object24AirSpaceVolumeIndex");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidIsNull() {
            addCriterion("object29_par_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidIsNotNull() {
            addCriterion("object29_par_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidEqualTo(String value) {
            addCriterion("object29_par_objid =", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidNotEqualTo(String value) {
            addCriterion("object29_par_objid <>", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidGreaterThan(String value) {
            addCriterion("object29_par_objid >", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object29_par_objid >=", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidLessThan(String value) {
            addCriterion("object29_par_objid <", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidLessThanOrEqualTo(String value) {
            addCriterion("object29_par_objid <=", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidLike(String value) {
            addCriterion("object29_par_objid like", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidNotLike(String value) {
            addCriterion("object29_par_objid not like", value, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidIn(List<String> values) {
            addCriterion("object29_par_objid in", values, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidNotIn(List<String> values) {
            addCriterion("object29_par_objid not in", values, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidBetween(String value1, String value2) {
            addCriterion("object29_par_objid between", value1, value2, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ParObjidNotBetween(String value1, String value2) {
            addCriterion("object29_par_objid not between", value1, value2, "object29ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidIsNull() {
            addCriterion("object29_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidIsNotNull() {
            addCriterion("object29_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidEqualTo(String value) {
            addCriterion("object29_objid =", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidNotEqualTo(String value) {
            addCriterion("object29_objid <>", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidGreaterThan(String value) {
            addCriterion("object29_objid >", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object29_objid >=", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidLessThan(String value) {
            addCriterion("object29_objid <", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidLessThanOrEqualTo(String value) {
            addCriterion("object29_objid <=", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidLike(String value) {
            addCriterion("object29_objid like", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidNotLike(String value) {
            addCriterion("object29_objid not like", value, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidIn(List<String> values) {
            addCriterion("object29_objid in", values, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidNotIn(List<String> values) {
            addCriterion("object29_objid not in", values, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidBetween(String value1, String value2) {
            addCriterion("object29_objid between", value1, value2, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29ObjidNotBetween(String value1, String value2) {
            addCriterion("object29_objid not between", value1, value2, "object29Objid");
            return (Criteria) this;
        }

        public Criteria andObject29GmlIsNull() {
            addCriterion("object29_gml is null");
            return (Criteria) this;
        }

        public Criteria andObject29GmlIsNotNull() {
            addCriterion("object29_gml is not null");
            return (Criteria) this;
        }

        public Criteria andObject29GmlEqualTo(String value) {
            addCriterion("object29_gml =", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlNotEqualTo(String value) {
            addCriterion("object29_gml <>", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlGreaterThan(String value) {
            addCriterion("object29_gml >", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlGreaterThanOrEqualTo(String value) {
            addCriterion("object29_gml >=", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlLessThan(String value) {
            addCriterion("object29_gml <", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlLessThanOrEqualTo(String value) {
            addCriterion("object29_gml <=", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlLike(String value) {
            addCriterion("object29_gml like", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlNotLike(String value) {
            addCriterion("object29_gml not like", value, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlIn(List<String> values) {
            addCriterion("object29_gml in", values, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlNotIn(List<String> values) {
            addCriterion("object29_gml not in", values, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlBetween(String value1, String value2) {
            addCriterion("object29_gml between", value1, value2, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject29GmlNotBetween(String value1, String value2) {
            addCriterion("object29_gml not between", value1, value2, "object29Gml");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidIsNull() {
            addCriterion("object38_par_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidIsNotNull() {
            addCriterion("object38_par_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidEqualTo(String value) {
            addCriterion("object38_par_objid =", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidNotEqualTo(String value) {
            addCriterion("object38_par_objid <>", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidGreaterThan(String value) {
            addCriterion("object38_par_objid >", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object38_par_objid >=", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidLessThan(String value) {
            addCriterion("object38_par_objid <", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidLessThanOrEqualTo(String value) {
            addCriterion("object38_par_objid <=", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidLike(String value) {
            addCriterion("object38_par_objid like", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidNotLike(String value) {
            addCriterion("object38_par_objid not like", value, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidIn(List<String> values) {
            addCriterion("object38_par_objid in", values, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidNotIn(List<String> values) {
            addCriterion("object38_par_objid not in", values, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidBetween(String value1, String value2) {
            addCriterion("object38_par_objid between", value1, value2, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ParObjidNotBetween(String value1, String value2) {
            addCriterion("object38_par_objid not between", value1, value2, "object38ParObjid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidIsNull() {
            addCriterion("object38_objid is null");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidIsNotNull() {
            addCriterion("object38_objid is not null");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidEqualTo(String value) {
            addCriterion("object38_objid =", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidNotEqualTo(String value) {
            addCriterion("object38_objid <>", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidGreaterThan(String value) {
            addCriterion("object38_objid >", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidGreaterThanOrEqualTo(String value) {
            addCriterion("object38_objid >=", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidLessThan(String value) {
            addCriterion("object38_objid <", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidLessThanOrEqualTo(String value) {
            addCriterion("object38_objid <=", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidLike(String value) {
            addCriterion("object38_objid like", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidNotLike(String value) {
            addCriterion("object38_objid not like", value, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidIn(List<String> values) {
            addCriterion("object38_objid in", values, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidNotIn(List<String> values) {
            addCriterion("object38_objid not in", values, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidBetween(String value1, String value2) {
            addCriterion("object38_objid between", value1, value2, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38ObjidNotBetween(String value1, String value2) {
            addCriterion("object38_objid not between", value1, value2, "object38Objid");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitIsNull() {
            addCriterion("object38_upperlimit is null");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitIsNotNull() {
            addCriterion("object38_upperlimit is not null");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitEqualTo(String value) {
            addCriterion("object38_upperlimit =", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitNotEqualTo(String value) {
            addCriterion("object38_upperlimit <>", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitGreaterThan(String value) {
            addCriterion("object38_upperlimit >", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitGreaterThanOrEqualTo(String value) {
            addCriterion("object38_upperlimit >=", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitLessThan(String value) {
            addCriterion("object38_upperlimit <", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitLessThanOrEqualTo(String value) {
            addCriterion("object38_upperlimit <=", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitLike(String value) {
            addCriterion("object38_upperlimit like", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitNotLike(String value) {
            addCriterion("object38_upperlimit not like", value, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitIn(List<String> values) {
            addCriterion("object38_upperlimit in", values, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitNotIn(List<String> values) {
            addCriterion("object38_upperlimit not in", values, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitBetween(String value1, String value2) {
            addCriterion("object38_upperlimit between", value1, value2, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38UpperlimitNotBetween(String value1, String value2) {
            addCriterion("object38_upperlimit not between", value1, value2, "object38Upperlimit");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexIsNull() {
            addCriterion("object38_horizontal_projection_index is null");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexIsNotNull() {
            addCriterion("object38_horizontal_projection_index is not null");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexEqualTo(Integer value) {
            addCriterion("object38_horizontal_projection_index =", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexNotEqualTo(Integer value) {
            addCriterion("object38_horizontal_projection_index <>", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexGreaterThan(Integer value) {
            addCriterion("object38_horizontal_projection_index >", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("object38_horizontal_projection_index >=", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexLessThan(Integer value) {
            addCriterion("object38_horizontal_projection_index <", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexLessThanOrEqualTo(Integer value) {
            addCriterion("object38_horizontal_projection_index <=", value, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexIn(List<Integer> values) {
            addCriterion("object38_horizontal_projection_index in", values, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexNotIn(List<Integer> values) {
            addCriterion("object38_horizontal_projection_index not in", values, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexBetween(Integer value1, Integer value2) {
            addCriterion("object38_horizontal_projection_index between", value1, value2, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andObject38HorizontalProjectionIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("object38_horizontal_projection_index not between", value1, value2, "object38HorizontalProjectionIndex");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(LocalDateTime value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(LocalDateTime value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(LocalDateTime value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(LocalDateTime value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<LocalDateTime> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<LocalDateTime> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(LocalDateTime value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(LocalDateTime value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(LocalDateTime value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(LocalDateTime value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<LocalDateTime> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<LocalDateTime> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 18 14:45:47 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}