package jp.go.meti.drone.swim.repository.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class SwimMaxFallRangeEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.business_number
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String businessNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.max_fall_range_id
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String maxFallRangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.operator_id
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.identifier
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String identifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.internal_identifier
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String internalIdentifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.swim_id
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String swimId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.enable
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.update_at
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private LocalDateTime updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range.create_at
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private LocalDateTime createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private static final long serialVersionUID = 1L;
}