package jp.go.meti.drone.swim.repository.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class SwimMaxFallRangeEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected boolean forUpdate;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public SwimMaxFallRangeEntityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public boolean isForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return forUpdate;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBusinessNumberIsNull() {
            addCriterion("business_number is null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIsNotNull() {
            addCriterion("business_number is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberEqualTo(String value) {
            addCriterion("business_number =", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotEqualTo(String value) {
            addCriterion("business_number <>", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThan(String value) {
            addCriterion("business_number >", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberGreaterThanOrEqualTo(String value) {
            addCriterion("business_number >=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThan(String value) {
            addCriterion("business_number <", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLessThanOrEqualTo(String value) {
            addCriterion("business_number <=", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberLike(String value) {
            addCriterion("business_number like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotLike(String value) {
            addCriterion("business_number not like", value, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberIn(List<String> values) {
            addCriterion("business_number in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotIn(List<String> values) {
            addCriterion("business_number not in", values, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberBetween(String value1, String value2) {
            addCriterion("business_number between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andBusinessNumberNotBetween(String value1, String value2) {
            addCriterion("business_number not between", value1, value2, "businessNumber");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIsNull() {
            addCriterion("max_fall_range_id is null");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIsNotNull() {
            addCriterion("max_fall_range_id is not null");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdEqualTo(String value) {
            addCriterion("max_fall_range_id =", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotEqualTo(String value) {
            addCriterion("max_fall_range_id <>", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdGreaterThan(String value) {
            addCriterion("max_fall_range_id >", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdGreaterThanOrEqualTo(String value) {
            addCriterion("max_fall_range_id >=", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLessThan(String value) {
            addCriterion("max_fall_range_id <", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLessThanOrEqualTo(String value) {
            addCriterion("max_fall_range_id <=", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdLike(String value) {
            addCriterion("max_fall_range_id like", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotLike(String value) {
            addCriterion("max_fall_range_id not like", value, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdIn(List<String> values) {
            addCriterion("max_fall_range_id in", values, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotIn(List<String> values) {
            addCriterion("max_fall_range_id not in", values, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdBetween(String value1, String value2) {
            addCriterion("max_fall_range_id between", value1, value2, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andMaxFallRangeIdNotBetween(String value1, String value2) {
            addCriterion("max_fall_range_id not between", value1, value2, "maxFallRangeId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(String value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(String value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(String value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(String value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(String value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(String value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLike(String value) {
            addCriterion("operator_id like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotLike(String value) {
            addCriterion("operator_id not like", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<String> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<String> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(String value1, String value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(String value1, String value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNull() {
            addCriterion("identifier is null");
            return (Criteria) this;
        }

        public Criteria andIdentifierIsNotNull() {
            addCriterion("identifier is not null");
            return (Criteria) this;
        }

        public Criteria andIdentifierEqualTo(String value) {
            addCriterion("identifier =", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotEqualTo(String value) {
            addCriterion("identifier <>", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThan(String value) {
            addCriterion("identifier >", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("identifier >=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThan(String value) {
            addCriterion("identifier <", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLessThanOrEqualTo(String value) {
            addCriterion("identifier <=", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierLike(String value) {
            addCriterion("identifier like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotLike(String value) {
            addCriterion("identifier not like", value, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierIn(List<String> values) {
            addCriterion("identifier in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotIn(List<String> values) {
            addCriterion("identifier not in", values, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierBetween(String value1, String value2) {
            addCriterion("identifier between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andIdentifierNotBetween(String value1, String value2) {
            addCriterion("identifier not between", value1, value2, "identifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierIsNull() {
            addCriterion("internal_identifier is null");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierIsNotNull() {
            addCriterion("internal_identifier is not null");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierEqualTo(String value) {
            addCriterion("internal_identifier =", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierNotEqualTo(String value) {
            addCriterion("internal_identifier <>", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierGreaterThan(String value) {
            addCriterion("internal_identifier >", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierGreaterThanOrEqualTo(String value) {
            addCriterion("internal_identifier >=", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierLessThan(String value) {
            addCriterion("internal_identifier <", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierLessThanOrEqualTo(String value) {
            addCriterion("internal_identifier <=", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierLike(String value) {
            addCriterion("internal_identifier like", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierNotLike(String value) {
            addCriterion("internal_identifier not like", value, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierIn(List<String> values) {
            addCriterion("internal_identifier in", values, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierNotIn(List<String> values) {
            addCriterion("internal_identifier not in", values, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierBetween(String value1, String value2) {
            addCriterion("internal_identifier between", value1, value2, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andInternalIdentifierNotBetween(String value1, String value2) {
            addCriterion("internal_identifier not between", value1, value2, "internalIdentifier");
            return (Criteria) this;
        }

        public Criteria andSwimIdIsNull() {
            addCriterion("swim_id is null");
            return (Criteria) this;
        }

        public Criteria andSwimIdIsNotNull() {
            addCriterion("swim_id is not null");
            return (Criteria) this;
        }

        public Criteria andSwimIdEqualTo(String value) {
            addCriterion("swim_id =", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdNotEqualTo(String value) {
            addCriterion("swim_id <>", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdGreaterThan(String value) {
            addCriterion("swim_id >", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdGreaterThanOrEqualTo(String value) {
            addCriterion("swim_id >=", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdLessThan(String value) {
            addCriterion("swim_id <", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdLessThanOrEqualTo(String value) {
            addCriterion("swim_id <=", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdLike(String value) {
            addCriterion("swim_id like", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdNotLike(String value) {
            addCriterion("swim_id not like", value, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdIn(List<String> values) {
            addCriterion("swim_id in", values, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdNotIn(List<String> values) {
            addCriterion("swim_id not in", values, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdBetween(String value1, String value2) {
            addCriterion("swim_id between", value1, value2, "swimId");
            return (Criteria) this;
        }

        public Criteria andSwimIdNotBetween(String value1, String value2) {
            addCriterion("swim_id not between", value1, value2, "swimId");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Boolean value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Boolean value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Boolean value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Boolean value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Boolean value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Boolean> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Boolean> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Boolean value1, Boolean value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(LocalDateTime value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(LocalDateTime value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(LocalDateTime value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(LocalDateTime value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<LocalDateTime> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<LocalDateTime> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(LocalDateTime value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(LocalDateTime value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(LocalDateTime value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(LocalDateTime value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<LocalDateTime> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<LocalDateTime> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 18 14:45:47 JST 2026
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swim_max_fall_range
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}