package jp.go.meti.drone.swim.repository.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class SwimMaxFallRangeHistoryEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.business_number
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String businessNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.max_fall_range_id
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String maxFallRangeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.history_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer historyIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_id
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String featureId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_timesliceid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String featureTimesliceid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_begin_position
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String featureBeginPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_end_position
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String featureEndPosition;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_designator
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String featureDesignator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_activation_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer featureActivationIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.feature_geometry_component_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer featureGeometryComponentIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object10_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object10Objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object10_timeinterval_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer object10TimeintervalIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object13_par_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object13ParObjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object13_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object13Objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object24_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object24Objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object24_air_space_volume_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer object24AirSpaceVolumeIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object29_par_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object29ParObjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object29_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object29Objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object29_gml
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object29Gml;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object38_par_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object38ParObjid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object38_objid
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object38Objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object38_upperlimit
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private String object38Upperlimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.object38_horizontal_projection_index
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Integer object38HorizontalProjectionIndex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.enable
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private Boolean enable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.update_at
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private LocalDateTime updateAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column swim_max_fall_range_history.create_at
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private LocalDateTime createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table swim_max_fall_range_history
     *
     * @mbg.generated Wed Feb 18 14:45:47 JST 2026
     */
    private static final long serialVersionUID = 1L;
}