spring.datasource:
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
  driver-class-name: org.h2.Driver
  username: sa
  password:

spring:
  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations:
        - classpath:schema.sql
#        - classpath:10900_create_batch.sql
      data-locations: classpath:data.sql

spring.h2.console.enabled: true