package jp.go.meti.drone.api.auth.repository.entity;

import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class DipsAccessEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.client_id
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.access_token
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String accessToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.expires_in
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private Integer expiresIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.refresh_expires_in
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private Integer refreshExpiresIn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.refresh_token
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String refreshToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.token_type
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String tokenType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.id_token
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String idToken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.not_before_policy
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private Integer notBeforePolicy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.session_state
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String sessionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.scope
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private String scope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.create_datetime
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private LocalDateTime createDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.update_datetime
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drone.dips_access_tokens.logic_delete_flag
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private Boolean logicDeleteFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    private static final long serialVersionUID = 1L;
}