package jp.go.meti.drone.api.auth.repository.entity;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class DipsAccessEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected boolean forUpdate;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public DipsAccessEntityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public void setForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public boolean isForUpdate(boolean forUpdate) {
        this.forUpdate = forUpdate;
        return forUpdate;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andClientIdIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClientIdIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClientIdEqualTo(String value) {
            addCriterion("client_id =", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotEqualTo(String value) {
            addCriterion("client_id <>", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThan(String value) {
            addCriterion("client_id >", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdGreaterThanOrEqualTo(String value) {
            addCriterion("client_id >=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThan(String value) {
            addCriterion("client_id <", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLessThanOrEqualTo(String value) {
            addCriterion("client_id <=", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdLike(String value) {
            addCriterion("client_id like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotLike(String value) {
            addCriterion("client_id not like", value, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdIn(List<String> values) {
            addCriterion("client_id in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotIn(List<String> values) {
            addCriterion("client_id not in", values, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdBetween(String value1, String value2) {
            addCriterion("client_id between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andClientIdNotBetween(String value1, String value2) {
            addCriterion("client_id not between", value1, value2, "clientId");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNull() {
            addCriterion("access_token is null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIsNotNull() {
            addCriterion("access_token is not null");
            return (Criteria) this;
        }

        public Criteria andAccessTokenEqualTo(String value) {
            addCriterion("access_token =", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotEqualTo(String value) {
            addCriterion("access_token <>", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThan(String value) {
            addCriterion("access_token >", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("access_token >=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThan(String value) {
            addCriterion("access_token <", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("access_token <=", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenLike(String value) {
            addCriterion("access_token like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotLike(String value) {
            addCriterion("access_token not like", value, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenIn(List<String> values) {
            addCriterion("access_token in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotIn(List<String> values) {
            addCriterion("access_token not in", values, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenBetween(String value1, String value2) {
            addCriterion("access_token between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andAccessTokenNotBetween(String value1, String value2) {
            addCriterion("access_token not between", value1, value2, "accessToken");
            return (Criteria) this;
        }

        public Criteria andExpiresInIsNull() {
            addCriterion("expires_in is null");
            return (Criteria) this;
        }

        public Criteria andExpiresInIsNotNull() {
            addCriterion("expires_in is not null");
            return (Criteria) this;
        }

        public Criteria andExpiresInEqualTo(Integer value) {
            addCriterion("expires_in =", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInNotEqualTo(Integer value) {
            addCriterion("expires_in <>", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInGreaterThan(Integer value) {
            addCriterion("expires_in >", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("expires_in >=", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInLessThan(Integer value) {
            addCriterion("expires_in <", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("expires_in <=", value, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInIn(List<Integer> values) {
            addCriterion("expires_in in", values, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInNotIn(List<Integer> values) {
            addCriterion("expires_in not in", values, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("expires_in between", value1, value2, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("expires_in not between", value1, value2, "expiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInIsNull() {
            addCriterion("refresh_expires_in is null");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInIsNotNull() {
            addCriterion("refresh_expires_in is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInEqualTo(Integer value) {
            addCriterion("refresh_expires_in =", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInNotEqualTo(Integer value) {
            addCriterion("refresh_expires_in <>", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInGreaterThan(Integer value) {
            addCriterion("refresh_expires_in >", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInGreaterThanOrEqualTo(Integer value) {
            addCriterion("refresh_expires_in >=", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInLessThan(Integer value) {
            addCriterion("refresh_expires_in <", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInLessThanOrEqualTo(Integer value) {
            addCriterion("refresh_expires_in <=", value, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInIn(List<Integer> values) {
            addCriterion("refresh_expires_in in", values, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInNotIn(List<Integer> values) {
            addCriterion("refresh_expires_in not in", values, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInBetween(Integer value1, Integer value2) {
            addCriterion("refresh_expires_in between", value1, value2, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshExpiresInNotBetween(Integer value1, Integer value2) {
            addCriterion("refresh_expires_in not between", value1, value2, "refreshExpiresIn");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIsNull() {
            addCriterion("refresh_token is null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIsNotNull() {
            addCriterion("refresh_token is not null");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenEqualTo(String value) {
            addCriterion("refresh_token =", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenNotEqualTo(String value) {
            addCriterion("refresh_token <>", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenGreaterThan(String value) {
            addCriterion("refresh_token >", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenGreaterThanOrEqualTo(String value) {
            addCriterion("refresh_token >=", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenLessThan(String value) {
            addCriterion("refresh_token <", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenLessThanOrEqualTo(String value) {
            addCriterion("refresh_token <=", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenLike(String value) {
            addCriterion("refresh_token like", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenNotLike(String value) {
            addCriterion("refresh_token not like", value, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenIn(List<String> values) {
            addCriterion("refresh_token in", values, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenNotIn(List<String> values) {
            addCriterion("refresh_token not in", values, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenBetween(String value1, String value2) {
            addCriterion("refresh_token between", value1, value2, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andRefreshTokenNotBetween(String value1, String value2) {
            addCriterion("refresh_token not between", value1, value2, "refreshToken");
            return (Criteria) this;
        }

        public Criteria andTokenTypeIsNull() {
            addCriterion("token_type is null");
            return (Criteria) this;
        }

        public Criteria andTokenTypeIsNotNull() {
            addCriterion("token_type is not null");
            return (Criteria) this;
        }

        public Criteria andTokenTypeEqualTo(String value) {
            addCriterion("token_type =", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeNotEqualTo(String value) {
            addCriterion("token_type <>", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeGreaterThan(String value) {
            addCriterion("token_type >", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeGreaterThanOrEqualTo(String value) {
            addCriterion("token_type >=", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeLessThan(String value) {
            addCriterion("token_type <", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeLessThanOrEqualTo(String value) {
            addCriterion("token_type <=", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeLike(String value) {
            addCriterion("token_type like", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeNotLike(String value) {
            addCriterion("token_type not like", value, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeIn(List<String> values) {
            addCriterion("token_type in", values, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeNotIn(List<String> values) {
            addCriterion("token_type not in", values, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeBetween(String value1, String value2) {
            addCriterion("token_type between", value1, value2, "tokenType");
            return (Criteria) this;
        }

        public Criteria andTokenTypeNotBetween(String value1, String value2) {
            addCriterion("token_type not between", value1, value2, "tokenType");
            return (Criteria) this;
        }

        public Criteria andIdTokenIsNull() {
            addCriterion("id_token is null");
            return (Criteria) this;
        }

        public Criteria andIdTokenIsNotNull() {
            addCriterion("id_token is not null");
            return (Criteria) this;
        }

        public Criteria andIdTokenEqualTo(String value) {
            addCriterion("id_token =", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenNotEqualTo(String value) {
            addCriterion("id_token <>", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenGreaterThan(String value) {
            addCriterion("id_token >", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenGreaterThanOrEqualTo(String value) {
            addCriterion("id_token >=", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenLessThan(String value) {
            addCriterion("id_token <", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenLessThanOrEqualTo(String value) {
            addCriterion("id_token <=", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenLike(String value) {
            addCriterion("id_token like", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenNotLike(String value) {
            addCriterion("id_token not like", value, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenIn(List<String> values) {
            addCriterion("id_token in", values, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenNotIn(List<String> values) {
            addCriterion("id_token not in", values, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenBetween(String value1, String value2) {
            addCriterion("id_token between", value1, value2, "idToken");
            return (Criteria) this;
        }

        public Criteria andIdTokenNotBetween(String value1, String value2) {
            addCriterion("id_token not between", value1, value2, "idToken");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyIsNull() {
            addCriterion("not_before_policy is null");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyIsNotNull() {
            addCriterion("not_before_policy is not null");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyEqualTo(Integer value) {
            addCriterion("not_before_policy =", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyNotEqualTo(Integer value) {
            addCriterion("not_before_policy <>", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyGreaterThan(Integer value) {
            addCriterion("not_before_policy >", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyGreaterThanOrEqualTo(Integer value) {
            addCriterion("not_before_policy >=", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyLessThan(Integer value) {
            addCriterion("not_before_policy <", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyLessThanOrEqualTo(Integer value) {
            addCriterion("not_before_policy <=", value, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyIn(List<Integer> values) {
            addCriterion("not_before_policy in", values, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyNotIn(List<Integer> values) {
            addCriterion("not_before_policy not in", values, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyBetween(Integer value1, Integer value2) {
            addCriterion("not_before_policy between", value1, value2, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andNotBeforePolicyNotBetween(Integer value1, Integer value2) {
            addCriterion("not_before_policy not between", value1, value2, "notBeforePolicy");
            return (Criteria) this;
        }

        public Criteria andSessionStateIsNull() {
            addCriterion("session_state is null");
            return (Criteria) this;
        }

        public Criteria andSessionStateIsNotNull() {
            addCriterion("session_state is not null");
            return (Criteria) this;
        }

        public Criteria andSessionStateEqualTo(String value) {
            addCriterion("session_state =", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateNotEqualTo(String value) {
            addCriterion("session_state <>", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateGreaterThan(String value) {
            addCriterion("session_state >", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateGreaterThanOrEqualTo(String value) {
            addCriterion("session_state >=", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateLessThan(String value) {
            addCriterion("session_state <", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateLessThanOrEqualTo(String value) {
            addCriterion("session_state <=", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateLike(String value) {
            addCriterion("session_state like", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateNotLike(String value) {
            addCriterion("session_state not like", value, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateIn(List<String> values) {
            addCriterion("session_state in", values, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateNotIn(List<String> values) {
            addCriterion("session_state not in", values, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateBetween(String value1, String value2) {
            addCriterion("session_state between", value1, value2, "sessionState");
            return (Criteria) this;
        }

        public Criteria andSessionStateNotBetween(String value1, String value2) {
            addCriterion("session_state not between", value1, value2, "sessionState");
            return (Criteria) this;
        }

        public Criteria andScopeIsNull() {
            addCriterion("scope is null");
            return (Criteria) this;
        }

        public Criteria andScopeIsNotNull() {
            addCriterion("scope is not null");
            return (Criteria) this;
        }

        public Criteria andScopeEqualTo(String value) {
            addCriterion("scope =", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotEqualTo(String value) {
            addCriterion("scope <>", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThan(String value) {
            addCriterion("scope >", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeGreaterThanOrEqualTo(String value) {
            addCriterion("scope >=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThan(String value) {
            addCriterion("scope <", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLessThanOrEqualTo(String value) {
            addCriterion("scope <=", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeLike(String value) {
            addCriterion("scope like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotLike(String value) {
            addCriterion("scope not like", value, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeIn(List<String> values) {
            addCriterion("scope in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotIn(List<String> values) {
            addCriterion("scope not in", values, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeBetween(String value1, String value2) {
            addCriterion("scope between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andScopeNotBetween(String value1, String value2) {
            addCriterion("scope not between", value1, value2, "scope");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(LocalDateTime value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(LocalDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagIsNull() {
            addCriterion("logic_delete_flag is null");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagIsNotNull() {
            addCriterion("logic_delete_flag is not null");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagEqualTo(Boolean value) {
            addCriterion("logic_delete_flag =", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("logic_delete_flag <>", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagGreaterThan(Boolean value) {
            addCriterion("logic_delete_flag >", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("logic_delete_flag >=", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagLessThan(Boolean value) {
            addCriterion("logic_delete_flag <", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("logic_delete_flag <=", value, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagIn(List<Boolean> values) {
            addCriterion("logic_delete_flag in", values, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("logic_delete_flag not in", values, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("logic_delete_flag between", value1, value2, "logicDeleteFlag");
            return (Criteria) this;
        }

        public Criteria andLogicDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("logic_delete_flag not between", value1, value2, "logicDeleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 25 17:38:22 JST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table drone.dips_access_tokens
     *
     * @mbg.generated Wed Sep 25 17:38:22 JST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}