package jp.go.meti.drone.relatedpartiesnotice.tenant.repository.entity;

import java.time.LocalDateTime;

import lombok.Data;

@Data
public class AirwayTenantAssociationEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.airway_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String airwayId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.operator_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String operatorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.creation_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private Integer creationId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.creation_datetime
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private LocalDateTime creationDatetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.update_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private Integer updateId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.airway_tenant_association.update_datetime
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private LocalDateTime updateDatetime;

}