package jp.go.meti.drone.relatedpartiesnotice.tenant.repository.entity;

import java.time.LocalDateTime;

import lombok.Data;

@Data
public class NotificationTargetInfoEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.operator_id
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private String operatorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.notification_target
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private String notificationTarget;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.notification_type
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private String notificationType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.creation_id
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private Integer creationId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.creation_datetime
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private LocalDateTime creationDatetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.update_id
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private Integer updateId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.notification_target_info.update_datetime
	 *
	 * @mbg.generated Wed Dec 04 10:58:04 JST 2024
	 */
	private LocalDateTime updateDatetime;

}
