package jp.go.meti.drone.relatedpartiesnotice.tenant.repository.entity;

import java.time.LocalDateTime;

import lombok.Data;

@Data
public class TenantEntity {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.operator_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String operatorId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.operator_name
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String operatorName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.user_type
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String userType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.notification_type
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String notificationType;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.role
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private String role;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.creation_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private Integer creationId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.creation_datetime
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private LocalDateTime creationDatetime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.update_id
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private Integer updateId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column droneairway2.tenant.update_datetime
	 *
	 * @mbg.generated Mon Dec 02 19:04:52 JST 2024
	 */
	private LocalDateTime updateDatetime;

}